version: "3"

volumes:
  vol-postgres:

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    # networks:
    # - internal
    volumes:
      - vol-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: insecure
      POSTGRES_HOST_AUTH_METHOD: password
    # https://stackoverflow.com/a/72175755
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 1s
    #   timeout: 5s
    #   retries: 60
  # pgmigrate:
  #   image: ghcr.io/peterldowns/pgmigrate:latest
  #   command: pgmigrate migrate
  #   networks:
  #   - internal
  #   volumes:
  #   - ./migrations:/migrations
  #   environment:
  #     PGM_MIGRATIONS: /migrations
  #     PGM_DATABASE: postgres://pg:insecure@postgres:5432
  #   depends_on:
  #     postgres:
  #       condition: service_healthy